src/Entity/Cateforie.php
<?php

namespace App\Entity;

use App\Repository\CateforieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CateforieRepository::class)
 */
class Cateforie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Titre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Description;

    /**
     * @ORM\OneToMany(targetEntity=Chaton::class, mappedBy="Categorie", orphanRemoval=true)
     */
    private $chatons;

    public function __construct()
    {
        $this->chatons = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @return Collection<int, Chaton>
     */
    public function getChatons(): Collection
    {
        return $this->chatons;
    }

    public function addChaton(Chaton $chaton): self
    {
        if (!$this->chatons->contains($chaton)) {
            $this->chatons[] = $chaton;
            $chaton->setCategorie($this);
        }

        return $this;
    }

    public function removeChaton(Chaton $chaton): self
    {
        if ($this->chatons->removeElement($chaton)) {
            // set the owning side to null (unless already changed)
            if ($chaton->getCategorie() === $this) {
                $chaton->setCategorie(null);
            }
        }

        return $this;
    }
}

src/Controller/CategoriesController.php
<?php

namespace App\Controller;

use App\Entity\Cateforie;
use App\Form\CategorieSupprimerType;
use App\Form\CategorieType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use function PHPUnit\Framework\throwException;

class CategoriesController extends AbstractController
{
    /**
     * @Route("/", name="app_categories")
     */
    public function index(ManagerRegistry $doctrine): Response
    {
        //Aller chercher les catégories dans la base
        //Donc on a besoins d'un repository
        $repo = $doctrine->getRepository(Cateforie::class);
        $categories = $repo->findAll(); //déclancher un select * qui devient une liste de catégorie

        return $this->render('categories/index.html.twig', [
            'categories'=>$categories
            ]);
    }

    /**
     * @Route("/categorie/ajouter", name="app_categories_ajouter")
     */
    public function ajouter(ManagerRegistry $doctrine, Request $request): Response
    {
        //Création du formulaire avant de le passer à la vue
        //Mais avant il faut créer une catégorie vide
        $categorie= new Cateforie();
        //A partir de ça je crée le formulaire
        $form=$this->createForm(CategorieType::class, $categorie);

        //On gère le retour du formulaire
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            //l'objet catégorie est rempli
            //Donc on dit a doctrine de le save dans la Bdd (on utilise un entity manager)
            $em=$doctrine->getManager();
            //et on dit à l'entity manager de mettre la catégorie en question dans la table
            $em->persist(($categorie));

            //on génère l'appel SQL (ici un insert)
            $em->flush();

            return $this->redirectToRoute("app_categories");
        }

        return $this->render("categories/ajouter.html.twig",[
            "formulaire"=>$form->createView()
        ]);
    }

    /**
     * @Route("/categorie/modifier/{id}", name="app_categories_modifier")
     */
    public function modifier($id, ManagerRegistry $doctrine, Request $request): Response
    {
        //créer le formulaire sur le même principe que dans ajouter
        //mais avec une catégorie existante
        $categorie = $doctrine->getRepository(Cateforie::class)->find($id); // select * from catégoire where id = ...

        //si l'id n'existe pas :
        if (!$categorie){
            throw $this->createNotFoundException("Pas de catégories avec l'id $id");
        }

        //si l'id existe :
        $form=$this->createForm(CategorieType::class, $categorie);

        //On gère le retour du formulaire
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            //l'objet catégorie est rempli
            //Donc on dit a doctrine de le save dans la Bdd (on utilise un entity manager)
            $em=$doctrine->getManager();
            //et on dit à l'entity manager de mettre la catégorie en question dans la table
            $em->persist(($categorie));

            //on génère l'appel SQL (ici un update)
            $em->flush();

            return $this->redirectToRoute("app_categories");
        }

        return $this->render("categories/modifier.html.twig",[
            "categorie"=>$categorie,
            "formulaire"=>$form->createView()
        ]);

    }

    /**
     * @Route("/categorie/supprimer/{id}", name="app_categories_supprimer")
     */
    public function supprimer($id, ManagerRegistry $doctrine, Request $request): Response
    {
        //créer le formulaire sur le même principe que dans ajouter
        //mais avec une catégorie existante
        $categorie = $doctrine->getRepository(Cateforie::class)->find($id); // select * from catégoire where id = ...

        //si l'id n'existe pas :
        if (!$categorie){
            throw $this->createNotFoundException("Pas de catégories avec l'id $id");
        }

        //si l'id existe :
        $form=$this->createForm(CategorieSupprimerType::class, $categorie);

        //On gère le retour du formulaire
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            //l'objet catégorie est rempli
            //Donc on dit a doctrine de le save dans la Bdd (on utilise un entity manager)
            $em=$doctrine->getManager();
            //et on dit à l'entity manager de mettre la catégorie en question dans la table de supprimer
            $em->remove(($categorie));

            //on génère l'appel SQL (ici un update)
            $em->flush();

            return $this->redirectToRoute("app_categories");
        }

        return $this->render("categories/supprimer.html.twig",[
            "categorie"=>$categorie,
            "formulaire"=>$form->createView()
        ]);

    }

}

templates/categories/ajouter.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une catégorie{% endblock %}

{% block body %}
    <div class="container">
    <h1>Ajouter une catégorie</h1>
    {{ form(formulaire) }}
    </div>
{% endblock %}

templates/categories/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Menu de gestion{% endblock %}

{% block body %}
    <div class="container">
        <h1>Gestion des chatons en Bdd</h1>
        <table class="table table-striped">
            <tr>
                <th>Titre</th>
                <th>Descriptions</th>
                <th></th>
            </tr>
            {% for c in categories %}
                <tr>
                    <td>{{ c.titre }}</td>
                    <td>{{ c.description }}</td>

                    <td>
                        <a class="btn btn-secondary" href="{{ path("app_categories_modifier", {"id":c.id}) }}">Modifier</a>
                        <a class="btn btn-danger" href="{{ path("app_categories_supprimer", {"id":c.id}) }}">Supprimer</a>
                        <a class="btn btn-primary" href="{{ path("app_chatons", {"id":c.id}) }}">Voir les chatons</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <a href="{{ path("app_categories_ajouter") }}" class="btn btn-success">Ajouter une categorie</a>
        <a href="{{ path("app_chaton_ajouter") }}" class="btn btn-success">Ajouter un chaton</a>
        <a href="{{ path('app_proprietaire_ajouter') }}" class="btn btn-success">Ajouter un propriétaire</a>
        <a href="{{ path('app_proprietaire_voir') }}" class="btn btn-success">Voir les propriétaires</a>
    </div>
{% endblock %}

templates/categories/modifier.html.twig
{% extends 'base.html.twig' %}

{% block title %}modifier une catégorie{% endblock %}

{% block body %}
    <div class="container">
        <h1>Modifier la catégorie <i>{{ categorie.titre }}</i></h1>
        {{ form(formulaire) }}
    </div>
{% endblock %}

templates/categories/supprimer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Supprimer une catégorie{% endblock %}

{% block body %}
    <div class="container">
        <h1>Supprimer une catégorie <i>{{ categorie.titre }}</i></h1>
        {{ form(formulaire) }}
        {# je vais mettre le bouton retour #}
        <a href="{{ path("app_categories") }}" class="btn btn-primary">Retour</a>
    </div>
{% endblock %}